CREATE TABLE OWNER ("ID" BIGINT NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY,"NAME" VARCHAR(255) NOT NULL,"IDCARDORCORPNUMBER" VARCHAR(255) NOT NULL,"ISCORP" BOOLEAN NOT NULL);

CREATE TABLE REALESTATE ("ID" BIGINT NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY,"CADASTRALAREA" VARCHAR(255) NOT NULL,"PARCELNUMBER" VARCHAR(255) NOT NULL,"AREAINMETERSSQUARED" DOUBLE NOT NULL);

CREATE TABLE OWNERSHIP ("ID" BIGINT NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY,"OWNERSHIPCREATED" TIMESTAMP NOT NULL,"OWNERSHIPREMOVED" TIMESTAMP,"SHARENUMERATOR" INTEGER NOT NULL,"SHAREDENOMINATOR" INTEGER NOT NULL,"OWNER" BIGINT REFERENCES OWNER(ID),"REALESTATE" BIGINT REFERENCES REALESTATE(ID));
