INSERT INTO OWNER (NAME, IDCARDORCORPNUMBER, ISCORP) VALUES ('Jack Owner', 'AB123456', FALSE);
INSERT INTO OWNER (NAME, IDCARDORCORPNUMBER, ISCORP) VALUES ('Dean Sanders', 'CD123456', FALSE);
INSERT INTO OWNER (NAME, IDCARDORCORPNUMBER, ISCORP) VALUES ('George Newman', 'ED123456', FALSE);
INSERT INTO OWNER (NAME, IDCARDORCORPNUMBER, ISCORP) VALUES ('John Vally', 'GH123456', FALSE);
INSERT INTO OWNER (NAME, IDCARDORCORPNUMBER, ISCORP) VALUES ('Julien Edelman', 'IJ123456', FALSE);
INSERT INTO OWNER (NAME, IDCARDORCORPNUMBER, ISCORP) VALUES ('ABC Inc.', 'ABCINC987', TRUE);
INSERT INTO OWNER (NAME, IDCARDORCORPNUMBER, ISCORP) VALUES ('Reads Company', 'RC987456321', TRUE);
INSERT INTO OWNER (NAME, IDCARDORCORPNUMBER, ISCORP) VALUES ('Navigation Holding', 'NAVH0001', TRUE);
INSERT INTO OWNER (NAME, IDCARDORCORPNUMBER, ISCORP) VALUES ('ANP a.s.', 'ANP000001', TRUE);
INSERT INTO OWNER (NAME, IDCARDORCORPNUMBER, ISCORP) VALUES ('RadioComapny1', 'RCOMP98', TRUE);

INSERT INTO REALESTATE (CADASTRALAREA, PARCELNUMBER, AREAINMETERSSQUARED) VALUES ('Villa 1', 'P13', 105);
INSERT INTO REALESTATE (CADASTRALAREA, PARCELNUMBER, AREAINMETERSSQUARED) VALUES ('Villa 2', 'P13', 105);
INSERT INTO REALESTATE (CADASTRALAREA, PARCELNUMBER, AREAINMETERSSQUARED) VALUES ('Villa 3', 'P14', 105);
INSERT INTO REALESTATE (CADASTRALAREA, PARCELNUMBER, AREAINMETERSSQUARED) VALUES ('Villa 4', 'P15', 105);
INSERT INTO REALESTATE (CADASTRALAREA, PARCELNUMBER, AREAINMETERSSQUARED) VALUES ('Villa 5', 'P16', 105);
INSERT INTO REALESTATE (CADASTRALAREA, PARCELNUMBER, AREAINMETERSSQUARED) VALUES ('Villa 6', 'P16', 105);
INSERT INTO REALESTATE (CADASTRALAREA, PARCELNUMBER, AREAINMETERSSQUARED) VALUES ('Villa 7', 'P16', 105);
INSERT INTO REALESTATE (CADASTRALAREA, PARCELNUMBER, AREAINMETERSSQUARED) VALUES ('Villa 8', 'P20', 105);
INSERT INTO REALESTATE (CADASTRALAREA, PARCELNUMBER, AREAINMETERSSQUARED) VALUES ('Villa 9', 'P21', 105);
INSERT INTO REALESTATE (CADASTRALAREA, PARCELNUMBER, AREAINMETERSSQUARED) VALUES ('Villa 10', 'P22', 105);

INSERT INTO OWNERSHIP (OWNER, REALESTATE, SHARENUMERATOR, SHAREDENOMINATOR, OWNERSHIPCREATED) VALUES ((SELECT ID FROM OWNER WHERE NAME='Jack Owner'), (SELECT ID FROM REALESTATE WHERE CADASTRALAREA='Villa 1'), 1, 4, CURRENT_TIMESTAMP);
INSERT INTO OWNERSHIP (OWNER, REALESTATE, SHARENUMERATOR, SHAREDENOMINATOR, OWNERSHIPCREATED) VALUES ((SELECT ID FROM OWNER WHERE NAME='Navigation Holding'), (SELECT ID FROM REALESTATE WHERE CADASTRALAREA='Villa 2'), 1, 1, CURRENT_TIMESTAMP);
